/**
 * Shared CMS content (custom pages + blog articles) for the demo tenant.
 * Used by `seed.ts` (full reset) and `refresh-content.ts` (live update
 * without wiping the database).
 */
export interface CustomPageSeed {
  title: string;
  slug: string;
  content: string;
}

export const CUSTOM_PAGES: CustomPageSeed[] = [
  {
    title: 'About',
    slug: 'about',
    content: `<p>Acme Academy is an online learning platform built around one simple idea: high-quality education should be accessible to everyone, everywhere. We bring together expert instructors and motivated learners in a single place where skills are taught practically — through real projects, clear explanations, and hands-on lessons you can apply immediately.</p><h2>What we offer</h2><ul><li><strong>Expert-led courses</strong> across development, design, business, marketing, data science, and photography — created by instructors with real industry experience.</li><li><strong>Learn at your own pace</strong> on any device, with lifetime access to every course you enroll in and progress tracking that keeps you on course.</li><li><strong>Certificates of completion</strong> for every finished course, so you can showcase new skills to employers and clients.</li><li><strong>A fair marketplace for instructors:</strong> teach what you know, reach a global audience, and earn revenue on every enrollment with transparent payouts.</li></ul><h2>How it works</h2><p><strong>For students:</strong> browse the catalog, add courses to your cart, and check out securely. Your courses appear in your dashboard instantly, where you can watch lessons, track progress, leave reviews, and download your certificate when you finish.</p><p><strong>For instructors:</strong> sign up as an instructor, build your course with chapters and lessons using the course builder, submit it for review, and start earning once it is published.</p><h2>Our promise</h2><p>Every course on Acme Academy is reviewed before publication, every purchase is covered by a 30-day money-back guarantee, and every learner gets the same thing we would want ourselves: honest content, fair pricing, and support when it matters. If you ever need help, reach us anytime via the <a href="/contact">contact page</a>.</p>`,
  },
  {
    title: 'Terms',
    slug: 'terms',
    content: `<p><em>Last updated: October 2026.</em> By creating an account or purchasing a course on this platform, you agree to the following terms.</p><h2>1. Accounts</h2><p>You must provide accurate information when registering and keep your password secure. You are responsible for all activity under your account. Instructors must additionally complete verification before publishing paid courses.</p><h2>2. Courses and enrollment</h2><p>Purchasing a course grants you a personal, non-transferable license to access it for as long as the course remains published. You may not share your account, resell access, or redistribute course materials, videos, or downloads.</p><h2>3. Payments and refunds</h2><p>All prices are shown in the platform currency at checkout. Payments are processed securely via our payment providers. If you are not satisfied with a course, you may request a refund within 30 days of purchase — no questions asked.</p><h2>4. Instructor terms</h2><p>Instructors earn revenue on each enrollment at the published commission rate, credited to their wallet. Payouts can be requested at any time and are processed after review. Courses must be original, accurate, and comply with our content guidelines; we may unpublish courses that violate them.</p><h2>5. Certificates</h2><p>Certificates of completion are issued automatically when you finish 100% of a course's lessons. They certify completion only and are not accredited academic qualifications.</p><h2>6. Acceptable use</h2><p>You agree not to misuse the platform, attempt to disrupt the service, upload unlawful content, or infringe intellectual property rights. We may suspend accounts that violate these terms.</p><h2>7. Changes</h2><p>We may update these terms from time to time. Continued use of the platform after changes take effect constitutes acceptance of the revised terms.</p>`,
  },
  {
    title: 'Privacy',
    slug: 'privacy',
    content: `<p><em>Last updated: October 2026.</em> This policy explains what data we collect, why, and how we protect it.</p><h2>1. Data we collect</h2><ul><li><strong>Account data:</strong> name, email address, password (stored hashed), and profile details you choose to add.</li><li><strong>Learning data:</strong> enrollments, lesson progress, watch history, reviews, and certificates.</li><li><strong>Payment data:</strong> order totals and transaction references. Full card details are handled by our payment providers and never stored on our servers.</li><li><strong>Support messages</strong> you send through the contact form.</li></ul><h2>2. How we use it</h2><p>We use your data to operate your account, deliver courses and certificates, process payments and payouts, provide support, and improve the platform. We do not sell your personal data to third parties.</p><h2>3. Cookies and sessions</h2><p>We use essential cookies and authentication tokens to keep you signed in and remember your preferences. No advertising trackers are used.</p><h2>4. Data sharing</h2><p>We share limited data only with service providers essential to the platform (hosting, payment processing, email delivery), each bound to protect it. Instructors can see the names of students enrolled in their own courses and nothing more.</p><h2>5. Your rights</h2><p>You may update your profile at any time, request a copy of your data, or request deletion of your account and associated data via the contact page. Deletion of enrollment records may affect issued certificates.</p><h2>6. Security</h2><p>Passwords are hashed with Argon2, traffic is encrypted in transit, and access to production data is restricted. No system is perfectly secure, but we follow industry best practices to protect your information.</p><h2>7. Contact</h2><p>Questions about privacy? Reach us anytime through the <a href="/contact">contact page</a>.</p>`,
  },
];

export interface BlogPostSeed {
  title: string;
  image: string;
  short: string;
  body: string;
}

export const BLOG_POSTS: BlogPostSeed[] = [
  {
    title: '10 Habits of Highly Effective Online Learners',
    image: 'blog_2_img_1.jpg',
    short: 'Small routines that make a big difference in how much you retain.',
    body: `<p>Online learning gives you freedom — but freedom demands structure. After watching thousands of students succeed (and stall) on this platform, we distilled the habits that separate finishers from starters.</p><h2>1. Learn in short, focused blocks</h2><p>Twenty-five to fifty minutes of undistracted study beats three hours of half-attention. Set a timer, close other tabs, and give one lesson your full focus.</p><h2>2. Take notes actively</h2><p>Pause the video and summarize each key idea in your own words. Rewriting forces understanding in a way highlighting never will.</p><h2>3. Build something every week</h2><p>Knowledge compounds when applied. After each chapter, create a small project, exercise, or write-up using what you just learned.</p><h2>4. Review on a schedule</h2><p>Revisit last week's notes before starting new material. Spaced repetition is the single most evidence-backed study technique we know.</p><h2>5. Ask questions early</h2><p>Stuck for more than 30 minutes? Ask in the course Q&amp;A instead of grinding in silence. Instructors here love good questions.</p><h2>6. Track your progress visibly</h2><p>Your dashboard shows completion per course — check it weekly. Momentum is motivating: a 60%-complete course pulls you forward.</p><h2>7. Teach what you learn</h2><p>Explain a concept to a friend, write a post, or answer another student's question. Teaching exposes gaps instantly.</p><h2>8. Protect a consistent time slot</h2><p>Same time, same place, most days. Habits beat motivation; a calendar block beats good intentions.</p><h2>9. Finish before you browse</h2><p>Resist starting five courses at once. Complete one, earn the certificate, then move on — depth beats breadth.</p><h2>10. Celebrate milestones</h2><p>Finished a hard chapter? Share your certificate and tell someone. Recognition fuels the next stretch.</p><p>Pick two habits from this list and start today. Your future self — certificate in hand — will thank you.</p>`,
  },
  {
    title: 'How to Choose Your First Programming Language',
    image: 'blog_2_img_2.jpg',
    short: 'A practical guide to picking a language that matches your goals.',
    body: `<p>The "best" first language depends on what you want to build. Here is an honest, goal-first breakdown.</p><h2>Want to build websites? Start with JavaScript</h2><p>JavaScript runs in every browser, powers interactive sites, and — with Node.js — servers too. Pair it with HTML and CSS, and you can ship visible results within weeks. Our <strong>Complete Web Development Bootcamp</strong> takes you from zero to full-stack on exactly this path.</p><h2>Interested in data, AI, or automation? Start with Python</h2><p>Python reads almost like English, has the richest ecosystem for data science and machine learning, and is a favorite for scripting and backends alike. Our <strong>Python for Data Science &amp; ML</strong> course is the natural next step.</p><h2>Curious about apps or systems?</h2><p>Swift and Kotlin lead to mobile apps, while C-family languages open doors to games and systems programming — but all are easier as a <em>second</em> language.</p><h2>The rule that matters most</h2><p>Any mainstream language teaches the same fundamentals: variables, control flow, functions, and problem decomposition. Pick one aligned with a project you care about, finish one beginner course completely, and build two small projects. Switching languages later is far easier than most beginners fear — quitting is the real risk, not choosing "wrong."</p>`,
  },
  {
    title: 'The Designer’s Guide to Building a Portfolio',
    image: 'blog_2_img_3.jpg',
    short: 'Show your process, not just polished screens.',
    body: `<p>Hiring managers spend minutes — sometimes seconds — on a first portfolio scan. What makes them stay is not pixel perfection; it is evidence of thinking.</p><h2>Lead with 3–4 strong case studies</h2><p>One deep case study beats ten shallow mockups. For each project, tell the story: the problem, your research, the constraints, the iterations, and the outcome — with numbers where possible.</p><h2>Show process, not just polish</h2><p>Include sketches, wireframes, dead ends, and the reasoning behind key decisions. Employers hire judgment, and judgment is visible only in process.</p><h2>Design for the role you want</h2><p>Applying to product roles? Show flows, systems thinking, and metrics. More visual roles? Emphasize craft, typography, and motion. Tailor the order of projects to each application.</p><h2>Sweat the basics</h2><p>Fast loading, readable type, working links, no lorem ipsum. A portfolio is itself a design artifact — it is judged as one.</p><h2>Keep it alive</h2><p>Add every course project worth showing, and prune anything older than your current skill level. A portfolio is never finished — and that is the point. Our <strong>UI/UX Design Masterclass</strong> includes a full module on packaging coursework into portfolio-ready case studies.</p>`,
  },
  {
    title: 'Breaking Into Data Science in 2026',
    image: 'blog_2_img_4.jpg',
    short: 'The skills, tools, and roadmap that actually matter today.',
    body: `<p>Data science has matured: employers now expect working skills over credentials. Here is a realistic roadmap for breaking in this year.</p><h2>Phase 1: Python and data wrangling (months 1–3)</h2><p>Master Python basics, then NumPy, pandas, and visualization. You should be able to take a messy CSV and produce clean, defensible insights. This is the foundation everything else rests on.</p><h2>Phase 2: Statistics and machine learning (months 3–6)</h2><p>Learn the intuition behind regression, classification, clustering, and validation — then implement them with scikit-learn on real datasets. Our <strong>Python for Data Science &amp; ML</strong> course covers exactly this arc.</p><h2>Phase 3: Specialize and ship (months 6–9)</h2><p>Pick a lane — analytics engineering, ML modeling, or deep learning with PyTorch — and publish 2–3 end-to-end projects on GitHub with clear write-ups. Deployed demos beat notebooks every time.</p><h2>What employers actually screen for</h2><ul><li><strong>SQL fluency</strong> — still the most requested data skill in job posts.</li><li><strong>Communication</strong> — can you explain a result to a non-technical stakeholder?</li><li><strong>Business sense</strong> — do your projects solve a plausible real problem?</li></ul><p>Certificates get you past filters; projects get you offers. Start with one course, finish it completely, and build in public as you go.</p>`,
  },
];
